[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, fails build when a category is below a threshold
[plugins.inputs.thresholds]
performance = 0.2
accessibility = 0.2
best-practices = 0.2
seo = 0.2
pwa = 0.2